services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    # overrides default command to avoid a shutdown of container before vscode established a connection
    # https://code.visualstudio.com/docs/remote/create-dev-container#_extend-your-docker-compose-file-for-development
    entrypoint: ["bash", "-c", "while sleep 1000; do :; done"]
    user: dev
    group_add:
      - "${DOCKER_SOCKET_GID:-800}"
    volumes:
      - type: bind
        source: ..
        target: /workspaces/zircon
      - type: bind
        source: ../.zircon
        target: /home/dev/.zircon
      - type: bind
        source: ${ZIRCON_NOTES_PATH:-../docs}
        target: /notes
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
