name: main
on:
  push:
    branches:
      - main
jobs:
  main:
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        platform:
          - name: amd64
            os: ubuntu-24.04
          # not yet supported for private repositories
          # - name: arm64
          #   os: ubuntu-24.04-arm
    runs-on: ${{ matrix.platform.os }}
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - name: Detect Docker socket group
        id: docker-socket
        run: echo "gid=$(stat -c '%g' /var/run/docker.sock)" >> "$GITHUB_OUTPUT"
      - uses: actions/cache/restore@v4
        with:
          path: |
            .pnpm-store
            .turbo
          key: cache-${{ matrix.platform.os }}
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: devcontainers/ci@v0.3
        env:
          DOCKER_SOCKET_GID: ${{ steps.docker-socket.outputs.gid }}
        with:
          imageName: ghcr.io/zirconhq/zircon/devcontainer
          cacheFrom: ghcr.io/zirconhq/zircon/devcontainer
          push: always
          env: |
            GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }}
          runCmd: turbo publish
      - uses: actions/cache/save@v4
        with:
          path: |
            .pnpm-store
            .turbo
          key: cache-${{ matrix.platform.os }}-${{ github.run_id }}
